build: Add Dockerfile & Dockerignore
alphayesodot/authentication-service pull request #3
Opened 2021-04-20 10:10 UTC by PCOffline

2021-04-20 10:22 UTC, yonatandt requested changes
The image could be lighter than this.

2021-04-20 10:22 UTC, yonatandt commented on Dockerfile
> +CMD ["npm", "run", "dev"]
`npm run dev`?
This should run in production, it is not the correct script to run.

2021-04-20 10:23 UTC, ShragaUser requested changes

2021-04-20 10:23 UTC, ShragaUser commented on Dockerfile
> +FROM node:14
The base Image should be an "alpine" typed one

2021-04-20 10:23 UTC, ShragaUser commented on Dockerfile
> +CMD ["npm", "run", "dev"]
Dockerfile should be production ready therefore usage of development mom script is wrong here.
Consider creating a dev.Dockerfile for development etc'

2021-04-20 10:23 UTC, ShragaUser commented on .dockerignore
> +dist
Environment files should also be ignored 
Be sure to add .env files and the like to docker ignore
Also IDE specific files

2021-04-20 16:05 UTC, ShragaUser requested changes

2021-04-20 16:05 UTC, ShragaUser commented on Dockerfile
> +FROM node:alpine
node version should be explicit.

2021-04-20 16:05 UTC, ShragaUser commented on Dockerfile
> +RUN npm install --silent
Should probably have production tag
No need for dev dependencies

2021-04-20 16:05 UTC, ShragaUser commented on Dockerfile
> +COPY . .
FYI
proper production docker files usually have multi-layer build 
Where only the dist is copied to a new layer and then run over nodejs without build dependencies. 

Not relevant in our case, but if you'd like a challenge, try to think about why this is the case and what can be done to improve this.

2021-04-22 07:47 UTC, yonatandt commented
@PCOffline Make sure you sign your commits.

2021-04-25 14:27 UTC, PCOffline commented
@yonatandt The node:14-alpine is already there. Probably a problem with File Changes

2021-04-25 15:01 UTC, yonatandt commented
@PCOffline Also in dev.Dockerfile?

2021-05-27 11:02 UTC, merged